version: "3.9"

services:
  bentopdf:
    image: bentopdf/bentopdf:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true # enable traefik
        - traefik.swarm.network=traefik-public # put it in the same network as traefik
        - traefik.constraint-label=traefik-public # assign the same label as traefik so it can be discovered
        - traefik.http.routers.bentopdf.rule=Host(`bentopdf.app.levell.ch`) # listen to port 80 for request to APP_DOMAIN (use together with the line below)
        - traefik.http.routers.bentopdf.entrypoints=http
        - traefik.http.routers.bentopdf.middlewares=https-redirect
        - traefik.http.middlewares.bentopdf.redirectscheme.scheme=https # redirect traffic to https
        - traefik.http.middlewares.bentopdf.redirectscheme.permanent=true # redirect traffic to https
        - traefik.http.routers.bentopdf-secured.rule=Host(`bentopdf.app.levell.ch`) # listen to port 443 for request to APP_DOMAIN (use together with the line below)
        - traefik.http.routers.bentopdf-secured.entrypoints=https
        - traefik.http.routers.bentopdf-secured.tls.certresolver=le # use the Let's Encrypt certificate we set up earlier
        - traefik.http.services.bentopdf-secured.loadbalancer.server.port=8080 # ask Traefik to search for port service container

networks:
  traefik-public:
    external: true
